channels:
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - librosa
  - cmake
  - ninja
  - pysoundfile
  - kaldi
  - scipy
  - pynini
  - openfst
  - setuptools_scm
  - pybind11
  - pytest
